version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  nodejs:
    build:
      context: ./nodejs
    volumes:
      - .:/home/node/data
    links:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
      - 5601:5601
    links:
      - elasticsearch
