version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  nodejs:
    build:
      context: ./nodejs
    volumes:
      - .:/home/node/data
    links:
      - elasticsearch
  kibana:
    image: kibana:7.5.1
    ports:
      - 5601:5601
    links:
      - elasticsearch

volumes:
  elasticsearch_data:
